** Save your ipython notebook with your name and push to bootcamp002_student/pythonWeek1Day3/**

# Part1: Numpy

## Array Creation
Construct the following arrays without listing all the elements. For example, you should use **np.ones(3)** to generate a array *array([1, 1, 1])* instead of **np.array([1, 1, 1])**.

(1) Construct an array of **float** ranging from 0-10.

In [1]:
### write your code here
import numpy as np
np.arange(10.5)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

(2) Create an array containing 7 evenly spaced numbers between 0 and 23.

In [2]:
### write your code here
np.arange(0,23,7)

array([ 0,  7, 14, 21])

(3) Create a 3x3 matrix with values ranging from 0 to 8.

In [6]:
### write your code here
from numpy import mat
m1 = mat([[1,2,3],[4,5,6],[7,8,9]])
m1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

(4) Create a 5x5 matrix with row values ranging from 0 to 4.

[Option] Is the result a copy-by-reference of copy-by-value?  If you change one cell, will it change other cells?

$$\left[
\begin{array}{cc}
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 
\end{array}
\right]$$

In [12]:
### write your code here
x=0
m2 = mat([[x,x+1,x+2,x+3,x+4],[x,x+1,x+2,x+3,x+4],[x,x+1,x+2,x+3,x+4],[x,x+1,x+2,x+3,x+4],[x,x+1,x+2,x+3,x+4]])
m2

matrix([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])

(5) A magic square is a matrix all of whose row sums, column sums and the sums of the two diagonals are the same. (One diagonal of a matrix goes from the top left to the bottom right, the other diagonal goes from top right to bottom left.)

Further more, a $n \times n$ magic matrix is constructed by $(1, 2, 3 ... n^2)$. For example, here is a $3\times 3$ magic array:
$$\left[
\begin{array}{cc}
8 & 1 & 6 \\
3 & 5 & 7 \\
4 & 9 & 2
\end{array}
\right]$$

Each number can only be used once.

Write a function to check whether a matrix is a magic matrix. You should check these three properties:

1. Is it a square matrix?
2. Is it constructed by $(1, 2, 3, ... n^2)$?
3. Are the sums of rows, columns and diags the same? (Hint: the function **np.diag** may be useful)


In [28]:
### write your code here
def isMagic(x):

    import numpy as np
    from numpy import mat
    from numpy import shape
    m1 = mat(x)
    shp = shape(m1)
    test1 = 'f'
    test2 = 'f'
    test3 = 'f'
    
    if shp[0]==shp[1]:
        print "Squared Matrix"
        test1 = 't'
    else:
        print "Not a squared matrix"

# Test 2
    rows = shp[0]
    cols = shp[1]
    a = []
    for i in range(rows):
        for j in range(cols):
            cell = m1[i,j]
            if cell >= 1 and cell <= (rows**2):
                
                if cell not in a:
                    a = a + cell
                    test2 = 't'
                else:
                    test2 = 'f'
                    break
            else:
                test2 = 'f'
                break
# Test 3   
    cols = shp[1]
    rowsum = []
    colsum = []
    diagsum = []
    n = 0
    p = 0
    r = 0
    for p in range(rows):
        for n in range(cols):
            r  = r + m1[p,n]
        rowsum.append(r)
        r = 0

    print rowsum

    c = 0
    for p in range(cols):
        for n in range(rows):
            c  = c + m1[n,p]
        colsum.append(c)
        c = 0
    print colsum

    diag1 = np.diag(m1)
    dsum1 = sum(diag1)
    diagsum.append(dsum1)
    diag2 =np.diag(np.fliplr(m1))
    dsum2 = sum(diag2)
    diagsum.append(dsum2)
    diagsum


    merge_rows_cols_sum = rowsum + colsum + diagsum
    print merge_rows_cols_sum


    def all_same(d):
        return all(e == d[0] for e in d)

    f_all = all_same(merge_rows_cols_sum)
    if f_all == True:
        test3 = 't'

    
# Now check the outcome of all the 3 tests
    if test1 == 't' and test2 =='t' and test3 == 't':
        print True
    else:
        print False

Here are some tests:

In [29]:
test1 = np.array([[0, 1], 
                  [1, 0]]) 
isMagic(test1) # False

Squared Matrix
[1, 1]
[1, 1]
[1, 1, 1, 1, 0, 2]
False


In [30]:
test2 = np.array([[8, 1, 6],
                  [3, 5, 7],
                  [4, 9, 2]])
isMagic(test2) # True

Squared Matrix
[15, 15, 15]
[15, 15, 15]
[15, 15, 15, 15, 15, 15, 15, 15]
True


In [31]:
test3 = np.array([[16, 2, 3, 13],
                  [5, 11, 10, 8],
                  [9,  7, 6, 12],
                  [4, 14, 15, 1]]) 
isMagic(test3) # True

Squared Matrix
[34, 34, 34, 34]
[34, 34, 34, 34]
[34, 34, 34, 34, 34, 34, 34, 34, 34, 34]
True


In [32]:
test4 = np.array([[17, 24,  1,  8, 15],
                  [23,  5,  7, 14, 16],
                  [4,   6, 13, 20, 22],
                  [10, 12, 19, 21,  3],
                  [11, 18, 25, 2,   9]]) 
isMagic(test4) # True

Squared Matrix
[65, 65, 65, 65, 65]
[65, 65, 65, 65, 65]
[65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65]
True


In [33]:
test5 = np.array([[35, 1, 6, 26, 19, 24],
                  [3, 32, 7, 21, 23, 25],
                  [31, 9, 2, 22, 27, 20],
                  [8, 28, 33, 17, 10,15],
                  [30, 5, 34, 12, 14,16],
                  [4, 36, 29, 13, 18,11]])
isMagic(test5) # True

Squared Matrix
[111, 111, 111, 111, 111, 111]
[111, 111, 111, 111, 111, 111]
[111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111, 111]
True


# Part 2: Scipy

(1) Generate a 100*2 array from a t distribution with degree 30.(Find t distribution in [the document](http://docs.scipy.org/doc/scipy/reference/stats.html))

In [43]:
### write your code here
import scipy
from scipy import stats
x = stats.t.rvs(30,size=200)
x

array([ -3.89885569e-01,   2.48612632e-01,   7.21664787e-01,
         1.45698487e+00,  -7.70238231e-01,   1.69490431e+00,
        -2.20903355e+00,   1.43974697e+00,   9.49845199e-01,
         1.56897824e+00,  -1.25256816e+00,   9.69521470e-01,
         1.65706450e+00,   9.78229793e-01,   2.96037315e-01,
         1.24139503e+00,   1.02852101e+00,  -5.42235116e-01,
         1.06577622e-01,  -1.05667953e+00,   6.38268974e-01,
        -1.32673287e+00,  -3.81224041e-01,  -1.12843572e+00,
        -7.37526758e-01,  -1.64472137e-01,  -8.64104025e-01,
         2.56130431e+00,   4.76132117e-01,  -1.48663156e+00,
        -6.63424066e-01,   7.06186277e-01,  -3.09403760e-01,
         2.86152667e+00,   5.24164108e-01,   8.55236398e-02,
        -7.45637981e-01,   4.12506612e-01,   3.37700192e+00,
         9.82243572e-02,   1.35257011e-01,  -1.21061884e-01,
        -2.94369351e-01,  -9.72706261e-02,   4.36765804e-01,
        -1.23833555e+00,   8.63652276e-01,  -2.66692214e-01,
         1.30891830e+00,

(2) According to this picture, does the "Petal Length" of different species has significant difference? Using the **Analysis of Variance** varify your answer.

![iris](http://www.nycdatascience.com/slides/BOOTCAMP2/content/week2/pic/scatter.png)

In [63]:
import pandas as pd
from numpy import array
iris = pd.read_csv('C:/Users/Anurag/Desktop/Python/iris.csv') # the iris.csv is in the zipped file
PetalLength = iris['Petal.Length']
Species = iris['Species']
pl = array(PetalLength)
sp = array(Species)
sp_num = []
print sp
for i in sp:
    if i == 'setosa':
        sp_num.append(1)
    if i == 'versicolor':
        sp_num.append(2)
    if i == 'virginica':
        sp_num.append(3)

print sp_num

['setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'v

In [65]:
### write your code here
stats.f_oneway(pl,sp_num)

(122.40119867012906, 4.5840145994250827e-24)